export const config = {
  LACCHAIN_PRIVATE_KEY: process.env.LACCHAIN_PRIVATE_KEY,
  LACCHAIN_PROVIDER: process.env.LACCHAIN_PROVIDER,
  LACCHAIN_NODE_ADDRESS: process.env.LACCHAIN_NODE_ADDRESS,
  LACCHAIN_EXPIRATION: process.env.LACCHAIN_EXPIRATION
};
